//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.ffice;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import aero.fixm.base.PersonOrOrganizationType;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A Unit involved in performing Air Traffic Management responsibilities as introduced in the PANS-ATM. [FF-ICE]
 * 
 * &lt;p&gt;Java class for AtmServiceProviderType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="AtmServiceProviderType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/app/ffice/1.1}AtmServiceProviderExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="provider" type="{http://www.fixm.aero/base/4.3}PersonOrOrganizationType" minOccurs="0"/&gt;
 *         &lt;element name="providerType" type="{http://www.fixm.aero/app/ffice/1.1}RoleTypeType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AtmServiceProviderType", propOrder = {
    "extension",
    "provider",
    "providerType"
})
@XmlSeeAlso({
    FficeFFPAtmServiceProviderType.class,
    FficeFAAtmServiceProviderType.class,
    FficeFCAtmServiceProviderType.class,
    FficeFDAtmServiceProviderType.class,
    FficeFPUAtmServiceProviderType.class,
    FficePFPAtmServiceProviderType.class,
    FficeTRQAtmServiceProviderType.class
})
public class AtmServiceProviderType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    protected List<AtmServiceProviderExtensionType> extension;
    /**
     * Identification information and associated communication address(es) for an ATM service provider.  [FF-ICE]
     * 
     */
    protected PersonOrOrganizationType provider;
    /**
     * Type of participant, FF-ICE or NON_FF-ICE [FIXM]
     * 
     */
    @XmlSchemaType(name = "string")
    protected RoleTypeType providerType;

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AtmServiceProviderExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<AtmServiceProviderExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Identification information and associated communication address(es) for an ATM service provider.  [FF-ICE]
     * 
     * @return
     *     possible object is
     *     {@link PersonOrOrganizationType }
     *     
     */
    public PersonOrOrganizationType getProvider() {
        return provider;
    }

    /**
     * Sets the value of the provider property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonOrOrganizationType }
     *     
     * @see #getProvider()
     */
    public void setProvider(PersonOrOrganizationType value) {
        this.provider = value;
    }

    /**
     * Type of participant, FF-ICE or NON_FF-ICE [FIXM]
     * 
     * @return
     *     possible object is
     *     {@link RoleTypeType }
     *     
     */
    public RoleTypeType getProviderType() {
        return providerType;
    }

    /**
     * Sets the value of the providerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleTypeType }
     *     
     * @see #getProviderType()
     */
    public void setProviderType(RoleTypeType value) {
        this.providerType = value;
    }

}
