//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.ffice;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The Filing Status provides information concerning the status of the route and trajectory, as submitted. [adapted from ICAO Draft FF-ICE Implementation Guidance ]
 * 
 * &lt;p&gt;Java class for FficeFS_FilingStatusType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficeFS_FilingStatusType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.fixm.aero/app/ffice/1.1}FilingStatusType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="expectedEvaluationTime" type="{http://www.fixm.aero/base/4.3}DateTimeUtcType" minOccurs="0"/&gt;
 *         &lt;element name="explanation" type="{http://www.fixm.aero/base/4.3}CharacterStringType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/app/ffice/1.1}FilingStatusExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="originator" type="{http://www.fixm.aero/base/4.3}FficeFS_PersonOrOrganizationType" minOccurs="0"/&gt;
 *         &lt;element name="trajectoryPurpose" type="{http://www.fixm.aero/app/ffice/1.1}TrajectoryPurposeType" minOccurs="0"/&gt;
 *         &lt;element name="value" type="{http://www.fixm.aero/app/ffice/1.1}FilingStatusValueType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficeFS_FilingStatusType")
public class FficeFSFilingStatusType
    extends FilingStatusType
    implements Serializable
{

    private static final long serialVersionUID = 1L;

}
