//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.ffice;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A status indicating if a message could be processed and acted on. [adapted from ICAO Draft FF-ICE Implementation Guidance]
 * 
 * &lt;p&gt;Java class for FficeSR_SubmissionStatusType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficeSR_SubmissionStatusType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.fixm.aero/app/ffice/1.1}SubmissionStatusType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="explanation" type="{http://www.fixm.aero/base/4.3}CharacterStringType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/app/ffice/1.1}SubmissionStatusExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="originator" type="{http://www.fixm.aero/base/4.3}FficeSR_PersonOrOrganizationType" minOccurs="0"/&gt;
 *         &lt;element name="value" type="{http://www.fixm.aero/app/ffice/1.1}SubmissionStatusValueType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficeSR_SubmissionStatusType")
public class FficeSRSubmissionStatusType
    extends SubmissionStatusType
    implements Serializable
{

    private static final long serialVersionUID = 1L;

}
