//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.ffice;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Represents the type of message. [FIXM]
 * 
 * &lt;p&gt;Java class for FficeTRQ_MessageTypeType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="FficeTRQ_MessageTypeType"&gt;
 *   &lt;restriction base="{http://www.fixm.aero/app/ffice/1.1}MessageTypeType"&gt;
 *     &lt;enumeration value="TRIAL_REQUEST"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "FficeTRQ_MessageTypeType")
@XmlEnum(MessageTypeType.class)
public enum FficeTRQMessageTypeType {


    /**
     * A Trial Request may be submitted to evaluate changes to either a Preliminary or Filed flight plan. Existing flight plan data will not be modified as a result of a Trial Request. [FF-ICE]
     * 
     */
    TRIAL_REQUEST;

    public String value() {
        return name();
    }

    public static FficeTRQMessageTypeType fromValue(String v) {
        return valueOf(v);
    }

}
