//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.ffice;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Represents the type of message. [FIXM]
 * 
 * &lt;p&gt;Java class for FficeFFP_MessageTypeType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="FficeFFP_MessageTypeType"&gt;
 *   &lt;restriction base="{http://www.fixm.aero/app/ffice/1.1}MessageTypeType"&gt;
 *     &lt;enumeration value="FILED_FLIGHT_PLAN"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "FficeFFP_MessageTypeType")
@XmlEnum(MessageTypeType.class)
public enum FficeFFPMessageTypeType {


    /**
     * The ATS flight plan as provided by the pilot or a designated representative. [FF-ICE]
     * 
     */
    FILED_FLIGHT_PLAN;

    public String value() {
        return name();
    }

    public static FficeFFPMessageTypeType fromValue(String v) {
        return valueOf(v);
    }

}
