//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.ffice;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A Unit involved in performing Air Traffic Management responsibilities as introduced in the PANS-ATM. [FF-ICE]
 * 
 * &lt;p&gt;Java class for FficeFC_AtmServiceProviderType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficeFC_AtmServiceProviderType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.fixm.aero/app/ffice/1.1}AtmServiceProviderType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/app/ffice/1.1}AtmServiceProviderExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="provider" type="{http://www.fixm.aero/base/4.3}PersonOrOrganizationType"/&gt;
 *         &lt;element name="providerType" type="{http://www.fixm.aero/app/ffice/1.1}RoleTypeType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficeFC_AtmServiceProviderType")
public class FficeFCAtmServiceProviderType
    extends AtmServiceProviderType
    implements Serializable
{

    private static final long serialVersionUID = 1L;

}
