//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.ffice;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A discrete unit of communication, expressed electronically, and intended by the source for consumption by some recipient or group of recipients. [FF-ICE]
 * 
 * &lt;p&gt;Java class for FficeFA_FficeMessageType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficeFA_FficeMessageType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.fixm.aero/app/ffice/1.1}FficeMessageType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/app/ffice/1.1}FficeMessageExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="flight" type="{http://www.fixm.aero/flight/4.3}FficeFA_FlightType"/&gt;
 *         &lt;element name="forwardingProvider" type="{http://www.fixm.aero/base/4.3}FficeFA_PersonOrOrganizationType" minOccurs="0"/&gt;
 *         &lt;element name="originator" type="{http://www.fixm.aero/base/4.3}FficeFA_PersonOrOrganizationType" minOccurs="0"/&gt;
 *         &lt;element name="recipient" type="{http://www.fixm.aero/base/4.3}FficeFA_PersonOrOrganizationType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="relevantAtmServiceProvider" type="{http://www.fixm.aero/app/ffice/1.1}FficeFA_AtmServiceProviderType" maxOccurs="2000"/&gt;
 *         &lt;element name="timestamp" type="{http://www.fixm.aero/base/4.3}DateTimeUtcHighPrecisionType" minOccurs="0"/&gt;
 *         &lt;element name="translationProvider" type="{http://www.fixm.aero/base/4.3}FficeFA_PersonOrOrganizationType" minOccurs="0"/&gt;
 *         &lt;element name="translationRecipient" type="{http://www.fixm.aero/base/4.3}PersonOrOrganizationType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="type" type="{http://www.fixm.aero/app/ffice/1.1}FficeFA_MessageTypeType" minOccurs="0"/&gt;
 *         &lt;element name="uniqueMessageIdentifier" type="{http://www.fixm.aero/base/4.3}UniversallyUniqueIdentifierType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficeFA_FficeMessageType")
public class FficeFAFficeMessageType
    extends FficeMessageType
    implements Serializable
{

    private static final long serialVersionUID = 1L;

}
