//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.ffice;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import aero.fixm.base.PersonOrOrganizationType;
import aero.fixm.base.UniversallyUniqueIdentifierType;
import aero.fixm.flight.FlightType;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A discrete unit of communication, expressed electronically, and intended by the source for consumption by some recipient or group of recipients. [FF-ICE]
 * 
 * &lt;p&gt;Java class for FficeMessageType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficeMessageType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/app/ffice/1.1}FficeMessageExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="filingStatus" type="{http://www.fixm.aero/app/ffice/1.1}FilingStatusType" minOccurs="0"/&gt;
 *         &lt;element name="flight" type="{http://www.fixm.aero/flight/4.3}FlightType" minOccurs="0"/&gt;
 *         &lt;element name="forwardingProvider" type="{http://www.fixm.aero/base/4.3}PersonOrOrganizationType" minOccurs="0"/&gt;
 *         &lt;element name="informationRequest" type="{http://www.fixm.aero/app/ffice/1.1}RequestedInformationChoiceType" minOccurs="0"/&gt;
 *         &lt;element name="operatorFlightPlanVersion" type="{http://www.fixm.aero/base/4.3}CountPositiveType" minOccurs="0"/&gt;
 *         &lt;element name="originator" type="{http://www.fixm.aero/base/4.3}PersonOrOrganizationType" minOccurs="0"/&gt;
 *         &lt;element name="planningStatus" type="{http://www.fixm.aero/app/ffice/1.1}PlanningStatusType" minOccurs="0"/&gt;
 *         &lt;element name="recipient" type="{http://www.fixm.aero/base/4.3}PersonOrOrganizationType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="referencedMessageIdentifier" type="{http://www.fixm.aero/base/4.3}UniversallyUniqueIdentifierType" minOccurs="0"/&gt;
 *         &lt;element name="relevantAtmServiceProvider" type="{http://www.fixm.aero/app/ffice/1.1}AtmServiceProviderType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="respondByLimit" type="{http://www.fixm.aero/base/4.3}DateTimeUtcType" minOccurs="0"/&gt;
 *         &lt;element name="submissionStatus" type="{http://www.fixm.aero/app/ffice/1.1}SubmissionStatusType" minOccurs="0"/&gt;
 *         &lt;element name="timestamp" type="{http://www.fixm.aero/base/4.3}DateTimeUtcHighPrecisionType" minOccurs="0"/&gt;
 *         &lt;element name="translationProvider" type="{http://www.fixm.aero/base/4.3}PersonOrOrganizationType" minOccurs="0"/&gt;
 *         &lt;element name="translationRecipient" type="{http://www.fixm.aero/base/4.3}PersonOrOrganizationType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="type" type="{http://www.fixm.aero/app/ffice/1.1}MessageTypeType" minOccurs="0"/&gt;
 *         &lt;element name="uniqueMessageIdentifier" type="{http://www.fixm.aero/base/4.3}UniversallyUniqueIdentifierType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficeMessageType", propOrder = {
    "extension",
    "filingStatus",
    "flight",
    "forwardingProvider",
    "informationRequest",
    "operatorFlightPlanVersion",
    "originator",
    "planningStatus",
    "recipient",
    "referencedMessageIdentifier",
    "relevantAtmServiceProvider",
    "respondByLimit",
    "submissionStatus",
    "timestamp",
    "translationProvider",
    "translationRecipient",
    "type",
    "uniqueMessageIdentifier"
})
@XmlSeeAlso({
    FficeFFPFficeMessageType.class,
    FficeFSFficeMessageType.class,
    FficeFAFficeMessageType.class,
    FficeFCFficeMessageType.class,
    FficeFDRQFficeMessageType.class,
    FficeFDRPFficeMessageType.class,
    FficeFDFficeMessageType.class,
    FficeFPUFficeMessageType.class,
    FficePSFficeMessageType.class,
    FficePFPFficeMessageType.class,
    FficeSRFficeMessageType.class,
    FficeTRQFficeMessageType.class,
    FficeTRPFficeMessageType.class
})
public class FficeMessageType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    protected List<FficeMessageExtensionType> extension;
    /**
     * The status of the filed flight plan with respect to the eASP.  [FF-ICE]
     * 
     */
    protected FilingStatusType filingStatus;
    /**
     * A flight associated with the message.
     * 
     */
    protected FlightType flight;
    /**
     * Identifies a provider that has been requested to forward the message to all Relevant ASPs. [FF-ICE]
     * 
     */
    protected PersonOrOrganizationType forwardingProvider;
    /**
     * Indicates what information about the flight is being requested.  [FF-ICE]
     * 
     */
    protected RequestedInformationChoiceType informationRequest;
    /**
     * A unique identifier for the latest version of a flight plan submitted by an Operator (Airspace User). A flight plan version should be operationally usable for verification that the pilot or operator and ATM personnel are using the same information for the flight. [adapted from ICAO Draft FF-ICE Implementation Guidance]. The identifier should begin at one and increase by one with each revision.
     * 
     */
    protected Integer operatorFlightPlanVersion;
    /**
     * Sender of the message [adapted from ICAO Draft FF-ICE Implementation Guidance]
     * 
     */
    protected PersonOrOrganizationType originator;
    /**
     * The status of the preliminary flight plan or trial request with respect to the eASP.  [FF-ICE]
     * 
     */
    protected PlanningStatusType planningStatus;
    /**
     * The one or more intended recipients of the flight information. [adapted from ICAO Draft FF-ICE Implementation Guidance]
     * 
     */
    protected List<PersonOrOrganizationType> recipient;
    /**
     * The unique message identifier of the message being responded to. [FIXM]
     * 
     */
    protected UniversallyUniqueIdentifierType referencedMessageIdentifier;
    /**
     * An ATM Service Provider whose airspace is entered by the flight plan route of flight or along the possible route of flight described in filed routing to a revised destination, and therefore should receive a flight plan from the operator of the flight. [FF-ICE]
     * 
     */
    protected List<AtmServiceProviderType> relevantAtmServiceProvider;
    /**
     * The limit, expressed as a time, by which a response is required. If the appropriate response has not been received within the time limit provided, the conditions under which the route/trajectory is proposed may no longer be available or valid.  [FF-ICE]
     * 
     */
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar respondByLimit;
    /**
     * A status indicating if a message could be processed and acted on. [adapted from ICAO Draft FF-ICE Implementation Guidance]
     * 
     */
    protected SubmissionStatusType submissionStatus;
    /**
     * The time and date that the communication was sent. [FIXM]
     * 
     */
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;
    /**
     * Identifies the provider that has been requested to translate and forward the message to identified translation recipients. [FF-ICE]
     * 
     */
    protected PersonOrOrganizationType translationProvider;
    /**
     * The one or more intended recipients of the translation and forwarding service.  [FF-ICE]
     * 
     */
    protected List<PersonOrOrganizationType> translationRecipient;
    /**
     * Represents the type of message. [FIXM]
     * 
     */
    @XmlSchemaType(name = "string")
    protected MessageTypeType type;
    /**
     * A unique message identifier for FIXM messages. [FIXM]
     * 
     */
    protected UniversallyUniqueIdentifierType uniqueMessageIdentifier;

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FficeMessageExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<FficeMessageExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * The status of the filed flight plan with respect to the eASP.  [FF-ICE]
     * 
     * @return
     *     possible object is
     *     {@link FilingStatusType }
     *     
     */
    public FilingStatusType getFilingStatus() {
        return filingStatus;
    }

    /**
     * Sets the value of the filingStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilingStatusType }
     *     
     * @see #getFilingStatus()
     */
    public void setFilingStatus(FilingStatusType value) {
        this.filingStatus = value;
    }

    /**
     * A flight associated with the message.
     * 
     * @return
     *     possible object is
     *     {@link FlightType }
     *     
     */
    public FlightType getFlight() {
        return flight;
    }

    /**
     * Sets the value of the flight property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightType }
     *     
     * @see #getFlight()
     */
    public void setFlight(FlightType value) {
        this.flight = value;
    }

    /**
     * Identifies a provider that has been requested to forward the message to all Relevant ASPs. [FF-ICE]
     * 
     * @return
     *     possible object is
     *     {@link PersonOrOrganizationType }
     *     
     */
    public PersonOrOrganizationType getForwardingProvider() {
        return forwardingProvider;
    }

    /**
     * Sets the value of the forwardingProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonOrOrganizationType }
     *     
     * @see #getForwardingProvider()
     */
    public void setForwardingProvider(PersonOrOrganizationType value) {
        this.forwardingProvider = value;
    }

    /**
     * Indicates what information about the flight is being requested.  [FF-ICE]
     * 
     * @return
     *     possible object is
     *     {@link RequestedInformationChoiceType }
     *     
     */
    public RequestedInformationChoiceType getInformationRequest() {
        return informationRequest;
    }

    /**
     * Sets the value of the informationRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestedInformationChoiceType }
     *     
     * @see #getInformationRequest()
     */
    public void setInformationRequest(RequestedInformationChoiceType value) {
        this.informationRequest = value;
    }

    /**
     * A unique identifier for the latest version of a flight plan submitted by an Operator (Airspace User). A flight plan version should be operationally usable for verification that the pilot or operator and ATM personnel are using the same information for the flight. [adapted from ICAO Draft FF-ICE Implementation Guidance]. The identifier should begin at one and increase by one with each revision.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOperatorFlightPlanVersion() {
        return operatorFlightPlanVersion;
    }

    /**
     * Sets the value of the operatorFlightPlanVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getOperatorFlightPlanVersion()
     */
    public void setOperatorFlightPlanVersion(Integer value) {
        this.operatorFlightPlanVersion = value;
    }

    /**
     * Sender of the message [adapted from ICAO Draft FF-ICE Implementation Guidance]
     * 
     * @return
     *     possible object is
     *     {@link PersonOrOrganizationType }
     *     
     */
    public PersonOrOrganizationType getOriginator() {
        return originator;
    }

    /**
     * Sets the value of the originator property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonOrOrganizationType }
     *     
     * @see #getOriginator()
     */
    public void setOriginator(PersonOrOrganizationType value) {
        this.originator = value;
    }

    /**
     * The status of the preliminary flight plan or trial request with respect to the eASP.  [FF-ICE]
     * 
     * @return
     *     possible object is
     *     {@link PlanningStatusType }
     *     
     */
    public PlanningStatusType getPlanningStatus() {
        return planningStatus;
    }

    /**
     * Sets the value of the planningStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanningStatusType }
     *     
     * @see #getPlanningStatus()
     */
    public void setPlanningStatus(PlanningStatusType value) {
        this.planningStatus = value;
    }

    /**
     * The one or more intended recipients of the flight information. [adapted from ICAO Draft FF-ICE Implementation Guidance]
     * 
     * Gets the value of the recipient property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the recipient property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getRecipient().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonOrOrganizationType }
     * </p>
     * 
     * 
     * @return
     *     The value of the recipient property.
     */
    public List<PersonOrOrganizationType> getRecipient() {
        if (recipient == null) {
            recipient = new ArrayList<>();
        }
        return this.recipient;
    }

    /**
     * The unique message identifier of the message being responded to. [FIXM]
     * 
     * @return
     *     possible object is
     *     {@link UniversallyUniqueIdentifierType }
     *     
     */
    public UniversallyUniqueIdentifierType getReferencedMessageIdentifier() {
        return referencedMessageIdentifier;
    }

    /**
     * Sets the value of the referencedMessageIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniversallyUniqueIdentifierType }
     *     
     * @see #getReferencedMessageIdentifier()
     */
    public void setReferencedMessageIdentifier(UniversallyUniqueIdentifierType value) {
        this.referencedMessageIdentifier = value;
    }

    /**
     * An ATM Service Provider whose airspace is entered by the flight plan route of flight or along the possible route of flight described in filed routing to a revised destination, and therefore should receive a flight plan from the operator of the flight. [FF-ICE]
     * 
     * Gets the value of the relevantAtmServiceProvider property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the relevantAtmServiceProvider property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getRelevantAtmServiceProvider().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AtmServiceProviderType }
     * </p>
     * 
     * 
     * @return
     *     The value of the relevantAtmServiceProvider property.
     */
    public List<AtmServiceProviderType> getRelevantAtmServiceProvider() {
        if (relevantAtmServiceProvider == null) {
            relevantAtmServiceProvider = new ArrayList<>();
        }
        return this.relevantAtmServiceProvider;
    }

    /**
     * The limit, expressed as a time, by which a response is required. If the appropriate response has not been received within the time limit provided, the conditions under which the route/trajectory is proposed may no longer be available or valid.  [FF-ICE]
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRespondByLimit() {
        return respondByLimit;
    }

    /**
     * Sets the value of the respondByLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     * @see #getRespondByLimit()
     */
    public void setRespondByLimit(XMLGregorianCalendar value) {
        this.respondByLimit = value;
    }

    /**
     * A status indicating if a message could be processed and acted on. [adapted from ICAO Draft FF-ICE Implementation Guidance]
     * 
     * @return
     *     possible object is
     *     {@link SubmissionStatusType }
     *     
     */
    public SubmissionStatusType getSubmissionStatus() {
        return submissionStatus;
    }

    /**
     * Sets the value of the submissionStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubmissionStatusType }
     *     
     * @see #getSubmissionStatus()
     */
    public void setSubmissionStatus(SubmissionStatusType value) {
        this.submissionStatus = value;
    }

    /**
     * The time and date that the communication was sent. [FIXM]
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     * @see #getTimestamp()
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

    /**
     * Identifies the provider that has been requested to translate and forward the message to identified translation recipients. [FF-ICE]
     * 
     * @return
     *     possible object is
     *     {@link PersonOrOrganizationType }
     *     
     */
    public PersonOrOrganizationType getTranslationProvider() {
        return translationProvider;
    }

    /**
     * Sets the value of the translationProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonOrOrganizationType }
     *     
     * @see #getTranslationProvider()
     */
    public void setTranslationProvider(PersonOrOrganizationType value) {
        this.translationProvider = value;
    }

    /**
     * The one or more intended recipients of the translation and forwarding service.  [FF-ICE]
     * 
     * Gets the value of the translationRecipient property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the translationRecipient property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getTranslationRecipient().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonOrOrganizationType }
     * </p>
     * 
     * 
     * @return
     *     The value of the translationRecipient property.
     */
    public List<PersonOrOrganizationType> getTranslationRecipient() {
        if (translationRecipient == null) {
            translationRecipient = new ArrayList<>();
        }
        return this.translationRecipient;
    }

    /**
     * Represents the type of message. [FIXM]
     * 
     * @return
     *     possible object is
     *     {@link MessageTypeType }
     *     
     */
    public MessageTypeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageTypeType }
     *     
     * @see #getType()
     */
    public void setType(MessageTypeType value) {
        this.type = value;
    }

    /**
     * A unique message identifier for FIXM messages. [FIXM]
     * 
     * @return
     *     possible object is
     *     {@link UniversallyUniqueIdentifierType }
     *     
     */
    public UniversallyUniqueIdentifierType getUniqueMessageIdentifier() {
        return uniqueMessageIdentifier;
    }

    /**
     * Sets the value of the uniqueMessageIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniversallyUniqueIdentifierType }
     *     
     * @see #getUniqueMessageIdentifier()
     */
    public void setUniqueMessageIdentifier(UniversallyUniqueIdentifierType value) {
        this.uniqueMessageIdentifier = value;
    }

}
