//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.ffice;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Represents the type of message. [FIXM]
 * 
 * &lt;p&gt;Java class for FficeFDRP_MessageTypeType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="FficeFDRP_MessageTypeType"&gt;
 *   &lt;restriction base="{http://www.fixm.aero/app/ffice/1.1}MessageTypeType"&gt;
 *     &lt;enumeration value="FLIGHT_DATA_RESPONSE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "FficeFDRP_MessageTypeType")
@XmlEnum(MessageTypeType.class)
public enum FficeFDRPMessageTypeType {


    /**
     * Used to return the information requested by a Flight Data Request. [FIXM]
     * 
     */
    FLIGHT_DATA_RESPONSE;

    public String value() {
        return name();
    }

    public static FficeFDRPMessageTypeType fromValue(String v) {
        return valueOf(v);
    }

}
