//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.ffice;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Represents the type of message. [FIXM]
 * 
 * &lt;p&gt;Java class for FficeFDRQ_MessageTypeType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="FficeFDRQ_MessageTypeType"&gt;
 *   &lt;restriction base="{http://www.fixm.aero/app/ffice/1.1}MessageTypeType"&gt;
 *     &lt;enumeration value="FLIGHT_DATA_REQUEST"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "FficeFDRQ_MessageTypeType")
@XmlEnum(MessageTypeType.class)
public enum FficeFDRQMessageTypeType {


    /**
     * Used to obtain information about a flight.  Designed to allow customized flight data queries, but the following should be a minimum set for implementation:
     * a) Flight Plan - request a copy of the flight plan as submitted.
     * b) Supplementary Plan - request a copy of the supplementary data filed for the flight.
     * c) Flight Status - request a copy of the latest Planning or Filing status for the flight.
     * [FF-ICE]
     * 
     */
    FLIGHT_DATA_REQUEST;

    public String value() {
        return name();
    }

    public static FficeFDRQMessageTypeType fromValue(String v) {
        return valueOf(v);
    }

}
