//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.ffice;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import aero.fixm.base.PersonOrOrganizationType;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The Filing Status provides information concerning the status of the route and trajectory, as submitted. [adapted from ICAO Draft FF-ICE Implementation Guidance ]
 * 
 * &lt;p&gt;Java class for FilingStatusType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FilingStatusType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="expectedEvaluationTime" type="{http://www.fixm.aero/base/4.3}DateTimeUtcType" minOccurs="0"/&gt;
 *         &lt;element name="explanation" type="{http://www.fixm.aero/base/4.3}CharacterStringType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/app/ffice/1.1}FilingStatusExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="originator" type="{http://www.fixm.aero/base/4.3}PersonOrOrganizationType" minOccurs="0"/&gt;
 *         &lt;element name="trajectoryPurpose" type="{http://www.fixm.aero/app/ffice/1.1}TrajectoryPurposeType" minOccurs="0"/&gt;
 *         &lt;element name="value" type="{http://www.fixm.aero/app/ffice/1.1}FilingStatusValueType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FilingStatusType", propOrder = {
    "expectedEvaluationTime",
    "explanation",
    "extension",
    "originator",
    "trajectoryPurpose",
    "value"
})
@XmlSeeAlso({
    FficeFSFilingStatusType.class
})
public class FilingStatusType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * The time at which an eASP expects to perform its first operational evaluation of the referenced eFPL. Optionally provided in association with a Filing Status of "PENDING".  [FF-ICE]
     * 
     */
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar expectedEvaluationTime;
    /**
     * Textual explanation of the returned status. [FF-ICE]
     * 
     */
    protected List<String> explanation;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    protected List<FilingStatusExtensionType> extension;
    /**
     * Identifies the originator of the Filing Status.  Provided when forwarding a Filing Status back to the originator of a forwarding request. [FF-ICE]
     * 
     */
    protected PersonOrOrganizationType originator;
    /**
     * An indication of the eASPs intended purpose in providing an Agreed R/T in a Filing Status.
     * 
     */
    @XmlSchemaType(name = "string")
    protected TrajectoryPurposeType trajectoryPurpose;
    /**
     * Possible values of an operational filing status (ACCEPTABLE, NOT_ACCEPTABLE, PENDING). [FF-ICE]
     * 
     */
    @XmlSchemaType(name = "string")
    protected FilingStatusValueType value;

    /**
     * The time at which an eASP expects to perform its first operational evaluation of the referenced eFPL. Optionally provided in association with a Filing Status of "PENDING".  [FF-ICE]
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpectedEvaluationTime() {
        return expectedEvaluationTime;
    }

    /**
     * Sets the value of the expectedEvaluationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     * @see #getExpectedEvaluationTime()
     */
    public void setExpectedEvaluationTime(XMLGregorianCalendar value) {
        this.expectedEvaluationTime = value;
    }

    /**
     * Textual explanation of the returned status. [FF-ICE]
     * 
     * Gets the value of the explanation property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the explanation property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExplanation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * </p>
     * 
     * 
     * @return
     *     The value of the explanation property.
     */
    public List<String> getExplanation() {
        if (explanation == null) {
            explanation = new ArrayList<>();
        }
        return this.explanation;
    }

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FilingStatusExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<FilingStatusExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Identifies the originator of the Filing Status.  Provided when forwarding a Filing Status back to the originator of a forwarding request. [FF-ICE]
     * 
     * @return
     *     possible object is
     *     {@link PersonOrOrganizationType }
     *     
     */
    public PersonOrOrganizationType getOriginator() {
        return originator;
    }

    /**
     * Sets the value of the originator property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonOrOrganizationType }
     *     
     * @see #getOriginator()
     */
    public void setOriginator(PersonOrOrganizationType value) {
        this.originator = value;
    }

    /**
     * An indication of the eASPs intended purpose in providing an Agreed R/T in a Filing Status.
     * 
     * @return
     *     possible object is
     *     {@link TrajectoryPurposeType }
     *     
     */
    public TrajectoryPurposeType getTrajectoryPurpose() {
        return trajectoryPurpose;
    }

    /**
     * Sets the value of the trajectoryPurpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrajectoryPurposeType }
     *     
     * @see #getTrajectoryPurpose()
     */
    public void setTrajectoryPurpose(TrajectoryPurposeType value) {
        this.trajectoryPurpose = value;
    }

    /**
     * Possible values of an operational filing status (ACCEPTABLE, NOT_ACCEPTABLE, PENDING). [FF-ICE]
     * 
     * @return
     *     possible object is
     *     {@link FilingStatusValueType }
     *     
     */
    public FilingStatusValueType getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilingStatusValueType }
     *     
     * @see #getValue()
     */
    public void setValue(FilingStatusValueType value) {
        this.value = value;
    }

}
