//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.ffice;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Possible values of an operational filing status (ACCEPTABLE, NOT_ACCEPTABLE, PENDING). [FF-ICE]
 * 
 * &lt;p&gt;Java class for FilingStatusValueType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="FilingStatusValueType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ACCEPTABLE"/&gt;
 *     &lt;enumeration value="NOT_ACCEPTABLE"/&gt;
 *     &lt;enumeration value="PENDING"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "FilingStatusValueType")
@XmlEnum
public enum FilingStatusValueType {


    /**
     * The flight plan and in particular the Filed Trajectory/route is acceptable. [FF-ICE]
     * 
     */
    ACCEPTABLE,

    /**
     * The flight plan, typically the route/trajectory, does not comply with operational requirements. [FF-ICE]
     * 
     */
    NOT_ACCEPTABLE,

    /**
     * The flight plan has not yet been evaluated by the eASP. [FF-ICE]
     * 
     */
    PENDING;

    public String value() {
        return name();
    }

    public static FilingStatusValueType fromValue(String v) {
        return valueOf(v);
    }

}
