//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.ffice;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Represents the type of message. [FIXM]
 * 
 * &lt;p&gt;Java class for MessageTypeType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="MessageTypeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="FILED_FLIGHT_PLAN"/&gt;
 *     &lt;enumeration value="FILING_STATUS"/&gt;
 *     &lt;enumeration value="FLIGHT_ARRIVAL"/&gt;
 *     &lt;enumeration value="FLIGHT_CANCELLATION"/&gt;
 *     &lt;enumeration value="FLIGHT_DATA_REQUEST"/&gt;
 *     &lt;enumeration value="FLIGHT_DATA_RESPONSE"/&gt;
 *     &lt;enumeration value="FLIGHT_DEPARTURE"/&gt;
 *     &lt;enumeration value="FLIGHT_PLAN_UPDATE"/&gt;
 *     &lt;enumeration value="PLANNING_STATUS"/&gt;
 *     &lt;enumeration value="PRELIMINARY_FLIGHT_PLAN"/&gt;
 *     &lt;enumeration value="SUBMISSION_RESPONSE"/&gt;
 *     &lt;enumeration value="TRIAL_REQUEST"/&gt;
 *     &lt;enumeration value="TRIAL_RESPONSE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "MessageTypeType")
@XmlEnum
public enum MessageTypeType {


    /**
     * The ATS flight plan as provided by the pilot or a designated representative. [FF-ICE]
     * 
     */
    FILED_FLIGHT_PLAN,

    /**
     * Provides information concerning the status of the filed flight plan and typically concerns route/trajectory acceptability. [FF-ICE]
     * 
     */
    FILING_STATUS,

    /**
     * A Flight Arrival message can be used in any situation where an ARR message would have been used per PANS-ATM 11.4.2.2.7. [FF-ICE]
     * 
     */
    FLIGHT_ARRIVAL,

    /**
     * Used to delete or remove a flight plan (Preliminary and/or Filed). [FF-ICE]
     * 
     */
    FLIGHT_CANCELLATION,

    /**
     * Used to obtain information about a flight.  Designed to allow customized flight data queries, but the following should be a minimum set for implementation:
     * a) Flight Plan - request a copy of the flight plan as submitted.
     * b) Supplementary Plan - request a copy of the supplementary data filed for the flight.
     * c) Flight Status - request a copy of the latest Planning or Filing status for the flight.
     * [FF-ICE]
     * 
     */
    FLIGHT_DATA_REQUEST,

    /**
     * Used to return the information requested by a Flight Data Request. [FIXM]
     * 
     */
    FLIGHT_DATA_RESPONSE,

    /**
     * A Flight Departure Message can be used in any situation where a DEP message would have been used per PANS-ATM 11.4.2.2.6. [FF-ICE]
     * 
     */
    FLIGHT_DEPARTURE,

    /**
     * A Flight Plan Update may be used to update either a Preliminary Flight Plan or a Filed Flight Plan. [FF-ICE]
     * 
     */
    FLIGHT_PLAN_UPDATE,

    /**
     * Provides information concerning the status of the preliminary flight plan and typically concerns route/trajectory acceptability. [FF-ICE]
     * 
     */
    PLANNING_STATUS,

    /**
     * Specified information submitted by an operator to conduct collaborative planning of a flight prior to submission of a Filed Flight Plan. [FF-ICE]
     * 
     */
    PRELIMINARY_FLIGHT_PLAN,

    /**
     * An immediate response provided by an eASP to the message originator indicating acceptance or rejection of the message received. [FF-ICE]
     * 
     */
    SUBMISSION_RESPONSE,

    /**
     * A Trial Request may be submitted to evaluate changes to either a Preliminary or Filed flight plan. Existing flight plan data will not be modified as a result of a Trial Request. [FF-ICE]
     * 
     */
    TRIAL_REQUEST,

    /**
     * Provides information concerning the status of a Trial Request and typically concerns route/trajectory acceptability. [FIXM]
     * 
     */
    TRIAL_RESPONSE;

    public String value() {
        return name();
    }

    public static MessageTypeType fromValue(String v) {
        return valueOf(v);
    }

}
