//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.ffice;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the aero.fixm.ffice package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _FficeMessage_QNAME = new QName("http://www.fixm.aero/app/ffice/1.1", "FficeMessage");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: aero.fixm.ffice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FficeMessageType }
     * 
     * @return
     *     the new instance of {@link FficeMessageType }
     */
    public FficeMessageType createFficeMessageType() {
        return new FficeMessageType();
    }

    /**
     * Create an instance of {@link AtmServiceProviderType }
     * 
     * @return
     *     the new instance of {@link AtmServiceProviderType }
     */
    public AtmServiceProviderType createAtmServiceProviderType() {
        return new AtmServiceProviderType();
    }

    /**
     * Create an instance of {@link FilingStatusType }
     * 
     * @return
     *     the new instance of {@link FilingStatusType }
     */
    public FilingStatusType createFilingStatusType() {
        return new FilingStatusType();
    }

    /**
     * Create an instance of {@link PlanningStatusType }
     * 
     * @return
     *     the new instance of {@link PlanningStatusType }
     */
    public PlanningStatusType createPlanningStatusType() {
        return new PlanningStatusType();
    }

    /**
     * Create an instance of {@link RequestedInformationChoiceType }
     * 
     * @return
     *     the new instance of {@link RequestedInformationChoiceType }
     */
    public RequestedInformationChoiceType createRequestedInformationChoiceType() {
        return new RequestedInformationChoiceType();
    }

    /**
     * Create an instance of {@link SubmissionStatusType }
     * 
     * @return
     *     the new instance of {@link SubmissionStatusType }
     */
    public SubmissionStatusType createSubmissionStatusType() {
        return new SubmissionStatusType();
    }

    /**
     * Create an instance of {@link FficeFFPAtmServiceProviderType }
     * 
     * @return
     *     the new instance of {@link FficeFFPAtmServiceProviderType }
     */
    public FficeFFPAtmServiceProviderType createFficeFFPAtmServiceProviderType() {
        return new FficeFFPAtmServiceProviderType();
    }

    /**
     * Create an instance of {@link FficeFFPFficeMessageType }
     * 
     * @return
     *     the new instance of {@link FficeFFPFficeMessageType }
     */
    public FficeFFPFficeMessageType createFficeFFPFficeMessageType() {
        return new FficeFFPFficeMessageType();
    }

    /**
     * Create an instance of {@link FficeFSFficeMessageType }
     * 
     * @return
     *     the new instance of {@link FficeFSFficeMessageType }
     */
    public FficeFSFficeMessageType createFficeFSFficeMessageType() {
        return new FficeFSFficeMessageType();
    }

    /**
     * Create an instance of {@link FficeFSFilingStatusType }
     * 
     * @return
     *     the new instance of {@link FficeFSFilingStatusType }
     */
    public FficeFSFilingStatusType createFficeFSFilingStatusType() {
        return new FficeFSFilingStatusType();
    }

    /**
     * Create an instance of {@link FficeFAAtmServiceProviderType }
     * 
     * @return
     *     the new instance of {@link FficeFAAtmServiceProviderType }
     */
    public FficeFAAtmServiceProviderType createFficeFAAtmServiceProviderType() {
        return new FficeFAAtmServiceProviderType();
    }

    /**
     * Create an instance of {@link FficeFAFficeMessageType }
     * 
     * @return
     *     the new instance of {@link FficeFAFficeMessageType }
     */
    public FficeFAFficeMessageType createFficeFAFficeMessageType() {
        return new FficeFAFficeMessageType();
    }

    /**
     * Create an instance of {@link FficeFCAtmServiceProviderType }
     * 
     * @return
     *     the new instance of {@link FficeFCAtmServiceProviderType }
     */
    public FficeFCAtmServiceProviderType createFficeFCAtmServiceProviderType() {
        return new FficeFCAtmServiceProviderType();
    }

    /**
     * Create an instance of {@link FficeFCFficeMessageType }
     * 
     * @return
     *     the new instance of {@link FficeFCFficeMessageType }
     */
    public FficeFCFficeMessageType createFficeFCFficeMessageType() {
        return new FficeFCFficeMessageType();
    }

    /**
     * Create an instance of {@link FficeFDRQFficeMessageType }
     * 
     * @return
     *     the new instance of {@link FficeFDRQFficeMessageType }
     */
    public FficeFDRQFficeMessageType createFficeFDRQFficeMessageType() {
        return new FficeFDRQFficeMessageType();
    }

    /**
     * Create an instance of {@link FficeFDRPFficeMessageType }
     * 
     * @return
     *     the new instance of {@link FficeFDRPFficeMessageType }
     */
    public FficeFDRPFficeMessageType createFficeFDRPFficeMessageType() {
        return new FficeFDRPFficeMessageType();
    }

    /**
     * Create an instance of {@link FficeFDAtmServiceProviderType }
     * 
     * @return
     *     the new instance of {@link FficeFDAtmServiceProviderType }
     */
    public FficeFDAtmServiceProviderType createFficeFDAtmServiceProviderType() {
        return new FficeFDAtmServiceProviderType();
    }

    /**
     * Create an instance of {@link FficeFDFficeMessageType }
     * 
     * @return
     *     the new instance of {@link FficeFDFficeMessageType }
     */
    public FficeFDFficeMessageType createFficeFDFficeMessageType() {
        return new FficeFDFficeMessageType();
    }

    /**
     * Create an instance of {@link FficeFPUAtmServiceProviderType }
     * 
     * @return
     *     the new instance of {@link FficeFPUAtmServiceProviderType }
     */
    public FficeFPUAtmServiceProviderType createFficeFPUAtmServiceProviderType() {
        return new FficeFPUAtmServiceProviderType();
    }

    /**
     * Create an instance of {@link FficeFPUFficeMessageType }
     * 
     * @return
     *     the new instance of {@link FficeFPUFficeMessageType }
     */
    public FficeFPUFficeMessageType createFficeFPUFficeMessageType() {
        return new FficeFPUFficeMessageType();
    }

    /**
     * Create an instance of {@link FficePSFficeMessageType }
     * 
     * @return
     *     the new instance of {@link FficePSFficeMessageType }
     */
    public FficePSFficeMessageType createFficePSFficeMessageType() {
        return new FficePSFficeMessageType();
    }

    /**
     * Create an instance of {@link FficePSPlanningStatusType }
     * 
     * @return
     *     the new instance of {@link FficePSPlanningStatusType }
     */
    public FficePSPlanningStatusType createFficePSPlanningStatusType() {
        return new FficePSPlanningStatusType();
    }

    /**
     * Create an instance of {@link FficePFPAtmServiceProviderType }
     * 
     * @return
     *     the new instance of {@link FficePFPAtmServiceProviderType }
     */
    public FficePFPAtmServiceProviderType createFficePFPAtmServiceProviderType() {
        return new FficePFPAtmServiceProviderType();
    }

    /**
     * Create an instance of {@link FficePFPFficeMessageType }
     * 
     * @return
     *     the new instance of {@link FficePFPFficeMessageType }
     */
    public FficePFPFficeMessageType createFficePFPFficeMessageType() {
        return new FficePFPFficeMessageType();
    }

    /**
     * Create an instance of {@link FficeSRFficeMessageType }
     * 
     * @return
     *     the new instance of {@link FficeSRFficeMessageType }
     */
    public FficeSRFficeMessageType createFficeSRFficeMessageType() {
        return new FficeSRFficeMessageType();
    }

    /**
     * Create an instance of {@link FficeSRSubmissionStatusType }
     * 
     * @return
     *     the new instance of {@link FficeSRSubmissionStatusType }
     */
    public FficeSRSubmissionStatusType createFficeSRSubmissionStatusType() {
        return new FficeSRSubmissionStatusType();
    }

    /**
     * Create an instance of {@link FficeTRQAtmServiceProviderType }
     * 
     * @return
     *     the new instance of {@link FficeTRQAtmServiceProviderType }
     */
    public FficeTRQAtmServiceProviderType createFficeTRQAtmServiceProviderType() {
        return new FficeTRQAtmServiceProviderType();
    }

    /**
     * Create an instance of {@link FficeTRQFficeMessageType }
     * 
     * @return
     *     the new instance of {@link FficeTRQFficeMessageType }
     */
    public FficeTRQFficeMessageType createFficeTRQFficeMessageType() {
        return new FficeTRQFficeMessageType();
    }

    /**
     * Create an instance of {@link FficeTRPFficeMessageType }
     * 
     * @return
     *     the new instance of {@link FficeTRPFficeMessageType }
     */
    public FficeTRPFficeMessageType createFficeTRPFficeMessageType() {
        return new FficeTRPFficeMessageType();
    }

    /**
     * Create an instance of {@link FficeTRPPlanningStatusType }
     * 
     * @return
     *     the new instance of {@link FficeTRPPlanningStatusType }
     */
    public FficeTRPPlanningStatusType createFficeTRPPlanningStatusType() {
        return new FficeTRPPlanningStatusType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FficeMessageType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FficeMessageType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/app/ffice/1.1", name = "FficeMessage")
    public JAXBElement<FficeMessageType> createFficeMessage(FficeMessageType value) {
        return new JAXBElement<>(_FficeMessage_QNAME, FficeMessageType.class, null, value);
    }

}
