//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.ffice;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The applicable planning status values (CONCUR, NON_CONCUR, NEGOTIATE) of the route and trajectory, as submitted. [FF-ICE]
 * 
 * &lt;p&gt;Java class for PlanningStatusValueType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="PlanningStatusValueType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CONCUR"/&gt;
 *     &lt;enumeration value="NEGOTIATE"/&gt;
 *     &lt;enumeration value="NON_CONCUR"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "PlanningStatusValueType")
@XmlEnum
public enum PlanningStatusValueType {


    /**
     * The flight plan and in particular the route and trajectory is acceptable without the need for modification.  This should mean that if the flight plan were to be filed, it would be accepted. [FF-ICE]
     * 
     */
    CONCUR,

    /**
     * The flight plan and in particular the route and trajectory is acceptable and would be accepted if filed. However the trajectory determined by the eASP has included additional constraints and/or has applied ATM configuration factors such as runway-in-use or Met data which may have resulted in a different trajectory. The operator is expected to assess the feedback and determine whether or not it wishes to amend it's Desired trajectory. [FF-ICE]
     * 
     */
    NEGOTIATE,

    /**
     * The flight plan does not comply with published airspace/route availability or published restrictions and would result in a rejection or an unacceptable status if the flight plan were to be filed. [FF-ICE]
     * 
     */
    NON_CONCUR;

    public String value() {
        return name();
    }

    public static PlanningStatusValueType fromValue(String v) {
        return valueOf(v);
    }

}
