//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.ffice;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The minimum set of flight information request types required by FF-ICE. [FF-ICE]
 * 
 * &lt;p&gt;Java class for RequestTypeType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="RequestTypeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="FLIGHT_PLAN"/&gt;
 *     &lt;enumeration value="FLIGHT_STATUS"/&gt;
 *     &lt;enumeration value="SUPPLEMENTARY_FLIGHT_PLAN"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "RequestTypeType")
@XmlEnum
public enum RequestTypeType {


    /**
     * Used to request the latest submitted flight plan. [FF-ICE]
     * 
     */
    FLIGHT_PLAN,

    /**
     * Used to request the latest status (Planning or Filing) from an eASP. [FF-ICE]
     * 
     */
    FLIGHT_STATUS,

    /**
     * Used to request the latest submitted search and rescue information. [FF-ICE]
     * 
     */
    SUPPLEMENTARY_FLIGHT_PLAN;

    public String value() {
        return name();
    }

    public static RequestTypeType fromValue(String v) {
        return valueOf(v);
    }

}
