//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.ffice;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Indicates what information about the flight is being requested.  [FF-ICE]
 * 
 * &lt;p&gt;Java class for RequestedInformationChoiceType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="RequestedInformationChoiceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="other" type="{http://www.fixm.aero/base/4.3}CharacterStringType"/&gt;
 *         &lt;element name="type" type="{http://www.fixm.aero/app/ffice/1.1}RequestTypeType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestedInformationChoiceType", propOrder = {
    "other",
    "type"
})
public class RequestedInformationChoiceType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * Used to represent any custom types established by a flight data request service.  [FF-ICE]
     * 
     */
    protected String other;
    /**
     * Indicates the type of information being requested. [FF-ICE]
     * 
     */
    @XmlSchemaType(name = "string")
    protected RequestTypeType type;

    /**
     * Used to represent any custom types established by a flight data request service.  [FF-ICE]
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOther() {
        return other;
    }

    /**
     * Sets the value of the other property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getOther()
     */
    public void setOther(String value) {
        this.other = value;
    }

    /**
     * Indicates the type of information being requested. [FF-ICE]
     * 
     * @return
     *     possible object is
     *     {@link RequestTypeType }
     *     
     */
    public RequestTypeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestTypeType }
     *     
     * @see #getType()
     */
    public void setType(RequestTypeType value) {
        this.type = value;
    }

}
