//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.ffice;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Type of participant, FF-ICE or NON_FF-ICE [FIXM]
 * 
 * &lt;p&gt;Java class for RoleTypeType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="RoleTypeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="FFICE_PARTICIPANT"/&gt;
 *     &lt;enumeration value="NON_FFICE_PARTICIPANT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "RoleTypeType")
@XmlEnum
public enum RoleTypeType {


    /**
     * An ASP that is capable of providing FF-ICE services. [FF-ICE]
     * 
     */
    FFICE_PARTICIPANT,

    /**
     * An ASP that is unable to provide FF-ICE services. [FF-ICE]
     * 
     */
    NON_FFICE_PARTICIPANT;

    public String value() {
        return name();
    }

    public static RoleTypeType fromValue(String v) {
        return valueOf(v);
    }

}
