//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.ffice;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import aero.fixm.base.PersonOrOrganizationType;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A status indicating if a message could be processed and acted on. [adapted from ICAO Draft FF-ICE Implementation Guidance]
 * 
 * &lt;p&gt;Java class for SubmissionStatusType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="SubmissionStatusType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="explanation" type="{http://www.fixm.aero/base/4.3}CharacterStringType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/app/ffice/1.1}SubmissionStatusExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="originator" type="{http://www.fixm.aero/base/4.3}PersonOrOrganizationType" minOccurs="0"/&gt;
 *         &lt;element name="value" type="{http://www.fixm.aero/app/ffice/1.1}SubmissionStatusValueType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubmissionStatusType", propOrder = {
    "explanation",
    "extension",
    "originator",
    "value"
})
@XmlSeeAlso({
    FficeSRSubmissionStatusType.class
})
public class SubmissionStatusType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * Textual explanation of the returned status. [FF-ICE]
     * 
     */
    protected List<String> explanation;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    protected List<SubmissionStatusExtensionType> extension;
    /**
     * Identifies the originator of the Submission Response.  Provided when forwarding a Submission Response back to the originator of a forwarding request. [FF-ICE]
     * 
     */
    protected PersonOrOrganizationType originator;
    /**
     * Possible values of a submission status (ACK, REJECT or MANUAL) [FF-ICE]
     * 
     */
    @XmlSchemaType(name = "string")
    protected SubmissionStatusValueType value;

    /**
     * Textual explanation of the returned status. [FF-ICE]
     * 
     * Gets the value of the explanation property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the explanation property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExplanation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * </p>
     * 
     * 
     * @return
     *     The value of the explanation property.
     */
    public List<String> getExplanation() {
        if (explanation == null) {
            explanation = new ArrayList<>();
        }
        return this.explanation;
    }

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubmissionStatusExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<SubmissionStatusExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Identifies the originator of the Submission Response.  Provided when forwarding a Submission Response back to the originator of a forwarding request. [FF-ICE]
     * 
     * @return
     *     possible object is
     *     {@link PersonOrOrganizationType }
     *     
     */
    public PersonOrOrganizationType getOriginator() {
        return originator;
    }

    /**
     * Sets the value of the originator property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonOrOrganizationType }
     *     
     * @see #getOriginator()
     */
    public void setOriginator(PersonOrOrganizationType value) {
        this.originator = value;
    }

    /**
     * Possible values of a submission status (ACK, REJECT or MANUAL) [FF-ICE]
     * 
     * @return
     *     possible object is
     *     {@link SubmissionStatusValueType }
     *     
     */
    public SubmissionStatusValueType getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubmissionStatusValueType }
     *     
     * @see #getValue()
     */
    public void setValue(SubmissionStatusValueType value) {
        this.value = value;
    }

}
