//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.ffice;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Possible values of a submission status (ACK, REJECT or MANUAL) [FF-ICE]
 * 
 * &lt;p&gt;Java class for SubmissionStatusValueType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="SubmissionStatusValueType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ACK"/&gt;
 *     &lt;enumeration value="MAN"/&gt;
 *     &lt;enumeration value="REJ"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "SubmissionStatusValueType")
@XmlEnum
public enum SubmissionStatusValueType {


    /**
     * An 'acknowledge' (ACK) response indicates that the message received can be processed by the eASP and will be acted upon. [FF-ICE]
     * 
     */
    ACK,

    /**
     * A 'manual' (MAN) response indicates that the message has been queued for manual processing. [FF-ICE]
     * 
     */
    MAN,

    /**
     * A 'rejected' (REJ) response indicates that the message received could not be processed.  The message has therefore not been processed or acted upon by the eASP and none of the data has been retained. [FF-ICE]
     * 
     */
    REJ;

    public String value() {
        return name();
    }

    public static SubmissionStatusValueType fromValue(String v) {
        return valueOf(v);
    }

}
