//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.ffice.bugfix;

import java.io.Serializable;
import aero.fixm.base.FlightExtensionType;
import aero.fixm.flight.FlightRulesCategoryType;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * An extension to the Flight class.
 * 
 * &lt;p&gt;Java class for FficeMessageBugFixFlightExtensionType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficeMessageBugFixFlightExtensionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fixm.aero/base/4.3}FlightExtensionType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="flightRulesCategory" type="{http://www.fixm.aero/flight/4.3}FlightRulesCategoryType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficeMessageBugFixFlightExtensionType", propOrder = {
    "flightRulesCategory"
})
public class FficeMessageBugFixFlightExtensionType
    extends FlightExtensionType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * FOR USE ONLY IN A FLIGHT DATA RESPONSE MESSAGE. The category of flight rules with which the pilot intends to comply. [ICAO Doc 4444, Appendix 2, Item 8]
     * 
     */
    @XmlSchemaType(name = "string")
    protected FlightRulesCategoryType flightRulesCategory;

    /**
     * FOR USE ONLY IN A FLIGHT DATA RESPONSE MESSAGE. The category of flight rules with which the pilot intends to comply. [ICAO Doc 4444, Appendix 2, Item 8]
     * 
     * @return
     *     possible object is
     *     {@link FlightRulesCategoryType }
     *     
     */
    public FlightRulesCategoryType getFlightRulesCategory() {
        return flightRulesCategory;
    }

    /**
     * Sets the value of the flightRulesCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightRulesCategoryType }
     *     
     * @see #getFlightRulesCategory()
     */
    public void setFlightRulesCategory(FlightRulesCategoryType value) {
        this.flightRulesCategory = value;
    }

}
