//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.ffice.bugfix;

import java.io.Serializable;
import aero.fixm.base.RouteTrajectoryElementExtensionType;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * An extension to the RouteTrajectoryElement class.
 * 
 * &lt;p&gt;Java class for FficeMessageBugFixRouteTrajectoryElementExtensionType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficeMessageBugFixRouteTrajectoryElementExtensionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fixm.aero/base/4.3}RouteTrajectoryElementExtensionType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="modifiedRouteItemReference" type="{http://www.fixm.aero/base/4.3}CharacterStringType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficeMessageBugFixRouteTrajectoryElementExtensionType", propOrder = {
    "modifiedRouteItemReference"
})
public class FficeMessageBugFixRouteTrajectoryElementExtensionType
    extends RouteTrajectoryElementExtensionType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * FOR USE ONLY IN A FILING STATUS, PLANNING STATUS OR TRIAL RESPONSE MESSAGE. A reference to an ATFM program name that modified the route.
     * 
     */
    protected String modifiedRouteItemReference;

    /**
     * FOR USE ONLY IN A FILING STATUS, PLANNING STATUS OR TRIAL RESPONSE MESSAGE. A reference to an ATFM program name that modified the route.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifiedRouteItemReference() {
        return modifiedRouteItemReference;
    }

    /**
     * Sets the value of the modifiedRouteItemReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getModifiedRouteItemReference()
     */
    public void setModifiedRouteItemReference(String value) {
        this.modifiedRouteItemReference = value;
    }

}
