//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The time constraint applicable to a specific point on the route.
 * 
 * &lt;p&gt;Java class for FfficeFPU_TimeConstraintType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FfficeFPU_TimeConstraintType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.fixm.aero/flight/4.3}TimeConstraintType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}TimeConstraintExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="timeSpecification" type="{http://www.fixm.aero/base/4.3}TimeChoiceType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FfficeFPU_TimeConstraintType")
public class FfficeFPUTimeConstraintType
    extends TimeConstraintType
    implements Serializable
{

    private static final long serialVersionUID = 1L;

}
