//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The capabilities of the flight comprising of the:
 * a) presence of relevant serviceable equipment on board the aircraft;
 * b) equipment and capabilities commensurate with flight crew qualifications; and
 * c) where applicable, authorization from the appropriate authority.
 * [FIXM]
 * 
 * &lt;p&gt;Java class for FficeFFP_FlightCapabilitiesType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficeFFP_FlightCapabilitiesType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.fixm.aero/flight/4.3}FlightCapabilitiesType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="communication" type="{http://www.fixm.aero/flight/4.3}CommunicationCapabilitiesType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}FlightCapabilitiesExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="navigation" type="{http://www.fixm.aero/flight/4.3}NavigationCapabilitiesType" minOccurs="0"/&gt;
 *         &lt;element name="standardCapabilities" type="{http://www.fixm.aero/flight/4.3}StandardCapabilitiesIndicatorType" minOccurs="0"/&gt;
 *         &lt;element name="surveillance" type="{http://www.fixm.aero/flight/4.3}SurveillanceCapabilitiesType" minOccurs="0"/&gt;
 *         &lt;element name="survival" type="{http://www.fixm.aero/flight/4.3}FficeFFP_SurvivalCapabilitiesType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficeFFP_FlightCapabilitiesType")
public class FficeFFPFlightCapabilitiesType
    extends FlightCapabilitiesType
    implements Serializable
{

    private static final long serialVersionUID = 1L;

}
