//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Groups information pertaining to the flight's departure.
 * 
 * &lt;p&gt;Java class for FficeTRQ_DepartureType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficeTRQ_DepartureType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.fixm.aero/flight/4.3}DepartureType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="airfileIndicator" type="{http://www.fixm.aero/flight/4.3}AirfileIndicatorType" minOccurs="0"/&gt;
 *         &lt;element name="airportSlotIdentification" type="{http://www.fixm.aero/base/4.3}AirportSlotIdentificationType" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="departureAerodrome" type="{http://www.fixm.aero/base/4.3}AerodromeReferenceType"/&gt;
 *           &lt;element name="departurePoint" type="{http://www.fixm.aero/flight/4.3}DeparturePointChoiceType"/&gt;
 *         &lt;/choice&gt;
 *         &lt;choice&gt;
 *           &lt;element name="estimatedOffBlockTime" type="{http://www.fixm.aero/base/4.3}DateTimeUtcType"/&gt;
 *           &lt;element name="estimatedRouteStartTime" type="{http://www.fixm.aero/base/4.3}DateTimeUtcType"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}DepartureExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="runwayDirection" type="{http://www.fixm.aero/base/4.3}RunwayDirectionDesignatorType" minOccurs="0"/&gt;
 *         &lt;element name="takeoffAlternateAerodrome" type="{http://www.fixm.aero/base/4.3}AerodromeReferenceType" maxOccurs="2" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficeTRQ_DepartureType")
public class FficeTRQDepartureType
    extends DepartureType
    implements Serializable
{

    private static final long serialVersionUID = 1L;

}
