//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Aircraft enabling the flight. [FIXM]
 * 
 * &lt;p&gt;Java class for FficeFFP_AircraftType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficeFFP_AircraftType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.fixm.aero/flight/4.3}AircraftType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="aircraftAddress" type="{http://www.fixm.aero/flight/4.3}AircraftAddressType" minOccurs="0"/&gt;
 *         &lt;element name="aircraftApproachCategory" type="{http://www.fixm.aero/flight/4.3}AircraftApproachCategoryType" minOccurs="0"/&gt;
 *         &lt;element name="aircraftType" type="{http://www.fixm.aero/flight/4.3}FficeFFP_AircraftTypeType" maxOccurs="2000"/&gt;
 *         &lt;element name="capabilities" type="{http://www.fixm.aero/flight/4.3}FficeFFP_FlightCapabilitiesType"/&gt;
 *         &lt;element name="coloursAndMarkings" type="{http://www.fixm.aero/base/4.3}CharacterStringType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}AircraftExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="registration" type="{http://www.fixm.aero/flight/4.3}AircraftRegistrationListType" minOccurs="0"/&gt;
 *         &lt;element name="wakeTurbulence" type="{http://www.fixm.aero/flight/4.3}WakeTurbulenceCategoryType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficeFFP_AircraftType")
public class FficeFFPAircraftType
    extends AircraftType
    implements Serializable
{

    private static final long serialVersionUID = 1L;

}
