//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Contains basic information about the Flight Route that pertains to the whole flight.
 * 
 * &lt;p&gt;Java class for FficePS_FlightRouteInformationType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficePS_FlightRouteInformationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.fixm.aero/flight/4.3}FlightRouteInformationType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cruisingLevel" type="{http://www.fixm.aero/base/4.3}FlightLevelOrAltitudeOrVfrChoiceType"/&gt;
 *         &lt;element name="cruisingSpeed" type="{http://www.fixm.aero/base/4.3}TrueAirspeedType"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}FlightRouteInformationExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="totalEstimatedElapsedTime" type="{http://www.fixm.aero/base/4.3}DurationType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficePS_FlightRouteInformationType")
public class FficePSFlightRouteInformationType
    extends FlightRouteInformationType
    implements Serializable
{

    private static final long serialVersionUID = 1L;

}
