//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Describes the cruise climb parameters at the point at which a cruise climb is planned to commence.  Includes the speed, the lower level and the upper level of the cruise climb.
 * 
 * &lt;p&gt;Java class for FficeFS_CruiseClimbStartType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficeFS_CruiseClimbStartType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.fixm.aero/flight/4.3}CruiseClimbStartType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}CruiseClimbStartExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="lowerLevel" type="{http://www.fixm.aero/base/4.3}FlightLevelOrAltitudeChoiceType"/&gt;
 *         &lt;element name="speed" type="{http://www.fixm.aero/base/4.3}TrueAirspeedType"/&gt;
 *         &lt;element name="upperLevel" type="{http://www.fixm.aero/flight/4.3}UpperLevelChoiceType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficeFS_CruiseClimbStartType")
public class FficeFSCruiseClimbStartType
    extends CruiseClimbStartType
    implements Serializable
{

    private static final long serialVersionUID = 1L;

}
