//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A portion of the route that can be at one of three levels as described below:
 * a) A Route Element defined by a Significant Point and the ATS Route (or direct route) to be followed until a change in route.
 * b) An Expanded Route Element defined by a Significant Point and the ATS Route (or direct route) to be followed until the next Significant Point, which may be along the same ATS Route.
 * c)A Trajectory Element defined by a geographic point and the ATS Route (or direct route) followed until the next trajectory point. [FF-ICE/1 Implementation Guidance Manual, Appendix B, Chapter B-3.2]
 * 
 * &lt;p&gt;Java class for FficeTRP_RouteTrajectoryElementType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficeTRP_RouteTrajectoryElementType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.fixm.aero/flight/4.3}RouteTrajectoryElementType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="alongRouteDistance" type="{http://www.fixm.aero/base/4.3}DistanceType" minOccurs="0"/&gt;
 *         &lt;element name="constraint" type="{http://www.fixm.aero/flight/4.3}FficeTRP_RouteTrajectoryConstraintType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="elementStartPoint" type="{http://www.fixm.aero/base/4.3}SignificantPointChoiceType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}RouteTrajectoryElementExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="flightRulesChange" type="{http://www.fixm.aero/flight/4.3}FlightRulesType" minOccurs="0"/&gt;
 *         &lt;element name="modified" type="{http://www.fixm.aero/flight/4.3}ModifiedRouteItemIndicatorType" minOccurs="0"/&gt;
 *         &lt;element name="plannedDelay" type="{http://www.fixm.aero/flight/4.3}FficeTRP_PlannedDelayType" minOccurs="0"/&gt;
 *         &lt;element name="point4D" type="{http://www.fixm.aero/flight/4.3}FficeTRP_TrajectoryPoint4DType" minOccurs="0"/&gt;
 *         &lt;element name="routeChange" type="{http://www.fixm.aero/flight/4.3}FficeTRP_RouteChangeType" minOccurs="0"/&gt;
 *         &lt;element name="routeDesignatorToNextElement" type="{http://www.fixm.aero/flight/4.3}RouteDesignatorToNextElementChoiceType" minOccurs="0"/&gt;
 *         &lt;element name="routeTruncationIndicator" type="{http://www.fixm.aero/flight/4.3}RouteTruncationIndicatorType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="seqNum" type="{http://www.fixm.aero/base/4.3}CountType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficeTRP_RouteTrajectoryElementType")
public class FficeTRPRouteTrajectoryElementType
    extends RouteTrajectoryElementType
    implements Serializable
{

    private static final long serialVersionUID = 1L;

}
