//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Describes a new planned altitude or level at the specified point at which the change is planned to commence.  (May also describe a point at which the altitude or level change is planned to be attained.)
 * 
 * &lt;p&gt;Java class for FficeFFP_CruisingLevelChangeType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficeFFP_CruisingLevelChangeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.fixm.aero/flight/4.3}CruisingLevelChangeType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="activation" type="{http://www.fixm.aero/flight/4.3}ActivationType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}CruisingLevelChangeExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="level" type="{http://www.fixm.aero/base/4.3}FlightLevelOrAltitudeChoiceType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficeFFP_CruisingLevelChangeType")
public class FficeFFPCruisingLevelChangeType
    extends CruisingLevelChangeType
    implements Serializable
{

    private static final long serialVersionUID = 1L;

}
