//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * This is the central object of the FIXM Logical Model. It groups all information about the flight. [FIXM]
 * 
 * &lt;p&gt;Java class for FficeFD_FlightType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficeFD_FlightType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.fixm.aero/flight/4.3}FlightType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="arrival" type="{http://www.fixm.aero/flight/4.3}FficeFD_ArrivalType"/&gt;
 *         &lt;element name="departure" type="{http://www.fixm.aero/flight/4.3}FficeFD_DepartureType"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}FlightExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="flightIdentification" type="{http://www.fixm.aero/flight/4.3}FficeFD_FlightIdentificationType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficeFD_FlightType")
public class FficeFDFlightType
    extends FlightType
    implements Serializable
{

    private static final long serialVersionUID = 1L;

}
