//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A container of flight identifying data. [FIXM]
 * 
 * &lt;p&gt;Java class for FficeSR_FlightIdentificationType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficeSR_FlightIdentificationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.fixm.aero/flight/4.3}FlightIdentificationType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}FlightIdentificationExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element name="gufi" type="{http://www.fixm.aero/base/4.3}GloballyUniqueFlightIdentifierType"/&gt;
 *           &lt;element name="gufiLegacy" type="{http://www.fixm.aero/base/4.3}UniversallyUniqueIdentifierType"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficeSR_FlightIdentificationType")
public class FficeSRFlightIdentificationType
    extends FlightIdentificationType
    implements Serializable
{

    private static final long serialVersionUID = 1L;

}
