//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The type of aircraft enabling the flight. [FIXM]
 * 
 * &lt;p&gt;Java class for FficeFFP_AircraftTypeType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficeFFP_AircraftTypeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.fixm.aero/flight/4.3}AircraftTypeType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="aircraftCount" type="{http://www.fixm.aero/base/4.3}CountPositiveType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}AircraftTypeExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="icaoAircraftTypeDesignator" type="{http://www.fixm.aero/base/4.3}AircraftTypeDesignatorType"/&gt;
 *           &lt;element name="otherAircraftType" type="{http://www.fixm.aero/base/4.3}CharacterStringType"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficeFFP_AircraftTypeType")
public class FficeFFPAircraftTypeType
    extends AircraftTypeType
    implements Serializable
{

    private static final long serialVersionUID = 1L;

}
