//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * International Air Transport Association (IATA) flight designator.  [FIXM]
 * 
 * &lt;p&gt;Java class for FficeTRQ_IataFlightDesignatorType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficeTRQ_IataFlightDesignatorType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.fixm.aero/flight/4.3}IataFlightDesignatorType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}IataFlightDesignatorExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="flightNumber" type="{http://www.fixm.aero/flight/4.3}FlightNumberType"/&gt;
 *         &lt;element name="iataOperatorCode" type="{http://www.fixm.aero/flight/4.3}IataOperatorCodeType"/&gt;
 *         &lt;element name="operationalSuffix" type="{http://www.fixm.aero/flight/4.3}OperationalSuffixType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficeTRQ_IataFlightDesignatorType")
public class FficeTRQIataFlightDesignatorType
    extends IataFlightDesignatorType
    implements Serializable
{

    private static final long serialVersionUID = 1L;

}
