//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A requested change that is applicable to a route or trajectory point. Can be any of the several defined requested changes.
 * 
 * &lt;p&gt;Java class for FficeFPU_RouteChangeType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficeFPU_RouteChangeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.fixm.aero/flight/4.3}RouteChangeType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cruiseClimbStart" type="{http://www.fixm.aero/flight/4.3}FficeFPU_CruiseClimbStartType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}RouteChangeExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="level" type="{http://www.fixm.aero/flight/4.3}FficeFPU_CruisingLevelChangeType" minOccurs="0"/&gt;
 *         &lt;element name="speed" type="{http://www.fixm.aero/flight/4.3}FficeFPU_CruisingSpeedChangeType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficeFPU_RouteChangeType")
public class FficeFPURouteChangeType
    extends RouteChangeType
    implements Serializable
{

    private static final long serialVersionUID = 1L;

}
