//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The emergency and survival equipments available on board the aircraft. [FIXM]
 * 
 * &lt;p&gt;Java class for FficeTRQ_SurvivalCapabilitiesType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficeTRQ_SurvivalCapabilitiesType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.fixm.aero/flight/4.3}SurvivalCapabilitiesType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dinghyInformation" type="{http://www.fixm.aero/flight/4.3}DinghiesType" minOccurs="0"/&gt;
 *         &lt;element name="emergencyRadioCapabilityType" type="{http://www.fixm.aero/flight/4.3}EmergencyRadioCapabilityTypeListType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}SurvivalCapabilitiesExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="lifeJacketType" type="{http://www.fixm.aero/flight/4.3}LifeJacketTypeListType" minOccurs="0"/&gt;
 *         &lt;element name="survivalEquipmentRemarks" type="{http://www.fixm.aero/base/4.3}CharacterStringType" minOccurs="0"/&gt;
 *         &lt;element name="survivalEquipmentType" type="{http://www.fixm.aero/flight/4.3}SurvivalEquipmentTypeListType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficeTRQ_SurvivalCapabilitiesType")
public class FficeTRQSurvivalCapabilitiesType
    extends SurvivalCapabilitiesType
    implements Serializable
{

    private static final long serialVersionUID = 1L;

}
