//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Describes any applicable properties of the trajectory point.  May include multiple properties per point.
 * 
 * &lt;p&gt;Java class for FficeTRQ_TrajectoryPointPropertyType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficeTRQ_TrajectoryPointPropertyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.fixm.aero/flight/4.3}TrajectoryPointPropertyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="description" type="{http://www.fixm.aero/base/4.3}CharacterStringType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}TrajectoryPointPropertyExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="propertyType" type="{http://www.fixm.aero/flight/4.3}TrajectoryPointPropertyTypeType"/&gt;
 *         &lt;element name="reference" type="{http://www.fixm.aero/flight/4.3}TrajectoryPointReferenceType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficeTRQ_TrajectoryPointPropertyType")
public class FficeTRQTrajectoryPointPropertyType
    extends TrajectoryPointPropertyType
    implements Serializable
{

    private static final long serialVersionUID = 1L;

}
