//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Defines the speed schedule for climb and descent of the aircraft through the crossover altitude.
 * 
 * &lt;p&gt;Java class for FficeTRP_SpeedScheduleType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficeTRP_SpeedScheduleType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.fixm.aero/flight/4.3}SpeedScheduleType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}SpeedScheduleExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="initialSpeed" type="{http://www.fixm.aero/base/4.3}IndicatedAirspeedType"/&gt;
 *         &lt;element name="subsequentSpeed" type="{http://www.fixm.aero/base/4.3}IndicatedAirspeedType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficeTRP_SpeedScheduleType")
public class FficeTRPSpeedScheduleType
    extends SpeedScheduleType
    implements Serializable
{

    private static final long serialVersionUID = 1L;

}
