//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A point in a performance climb or descent profile.
 * 
 * &lt;p&gt;Java class for FficePS_ProfilePointType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficePS_ProfilePointType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.fixm.aero/flight/4.3}ProfilePointType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="airspeed" type="{http://www.fixm.aero/base/4.3}TrueAirspeedType" minOccurs="0"/&gt;
 *         &lt;element name="distance" type="{http://www.fixm.aero/base/4.3}DistanceType"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}ProfilePointExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="level" type="{http://www.fixm.aero/base/4.3}FlightLevelOrAltitudeChoiceType"/&gt;
 *         &lt;element name="time" type="{http://www.fixm.aero/base/4.3}DurationType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="seqNum" type="{http://www.fixm.aero/base/4.3}CountType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficePS_ProfilePointType")
public class FficePSProfilePointType
    extends ProfilePointType
    implements Serializable
{

    private static final long serialVersionUID = 1L;

}
