//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Identifies relevant information about a trajectory point including location, altitude, time, etc.
 * 
 * &lt;p&gt;Java class for FficeFPU_TrajectoryPoint4DType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficeFPU_TrajectoryPoint4DType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.fixm.aero/flight/4.3}TrajectoryPoint4DType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="altimeterSetting" type="{http://www.fixm.aero/base/4.3}PressureType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}TrajectoryPoint4DExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="level" type="{http://www.fixm.aero/base/4.3}FlightLevelOrAltitudeChoiceType"/&gt;
 *         &lt;element name="metData" type="{http://www.fixm.aero/flight/4.3}MeteorologicalDataType" minOccurs="0"/&gt;
 *         &lt;element name="pointProperty" type="{http://www.fixm.aero/flight/4.3}FficeFPU_TrajectoryPointPropertyType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="position" type="{http://www.fixm.aero/base/4.3}GeographicalPositionType"/&gt;
 *         &lt;element name="predictedAirspeed" type="{http://www.fixm.aero/base/4.3}IndicatedAirspeedType" minOccurs="0"/&gt;
 *         &lt;element name="predictedGroundspeed" type="{http://www.fixm.aero/base/4.3}GroundSpeedType" minOccurs="0"/&gt;
 *         &lt;element name="time" type="{http://www.fixm.aero/flight/4.3}Point4DTimeChoiceType"/&gt;
 *         &lt;element name="verticalRange" type="{http://www.fixm.aero/base/4.3}VerticalRangeType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficeFPU_TrajectoryPoint4DType")
public class FficeFPUTrajectoryPoint4DType
    extends TrajectoryPoint4DType
    implements Serializable
{

    private static final long serialVersionUID = 1L;

}
