//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A zero-wind, standard atmosphere, unconstrained movement profile reflective of the flight capabilities and desired parameters during climb or descent.
 * 
 * &lt;p&gt;Java class for FficeFS_PerformanceProfileType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficeFS_PerformanceProfileType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.fixm.aero/flight/4.3}PerformanceProfileType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}PerformanceProfileExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="profilePoint" type="{http://www.fixm.aero/flight/4.3}FficeFS_ProfilePointType" maxOccurs="2000"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficeFS_PerformanceProfileType")
public class FficeFSPerformanceProfileType
    extends PerformanceProfileType
    implements Serializable
{

    private static final long serialVersionUID = 1L;

}
