//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The time, type of time (wheels-off, off blocks, etc.), and geographical position of the departure.  [FIXM]
 * 
 * &lt;p&gt;Java class for FficeFD_ActualTimeOfDepartureType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficeFD_ActualTimeOfDepartureType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.fixm.aero/flight/4.3}ActualTimeOfDepartureType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}ActualTimeOfDepartureExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="position" type="{http://www.fixm.aero/base/4.3}GeographicalPositionType" minOccurs="0"/&gt;
 *         &lt;element name="time" type="{http://www.fixm.aero/base/4.3}DateTimeUtcType"/&gt;
 *         &lt;element name="type" type="{http://www.fixm.aero/flight/4.3}DepartureTimeTypeType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficeFD_ActualTimeOfDepartureType")
public class FficeFDActualTimeOfDepartureType
    extends ActualTimeOfDepartureType
    implements Serializable
{

    private static final long serialVersionUID = 1L;

}
