//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Delay or holding planned to occur at a significant point or along a route element.
 * 
 * &lt;p&gt;Java class for FficeTRQ_PlannedDelayType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficeTRQ_PlannedDelayType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.fixm.aero/flight/4.3}PlannedDelayType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="delayReason" type="{http://www.fixm.aero/base/4.3}CharacterStringType"/&gt;
 *         &lt;element name="delayReference" type="{http://www.fixm.aero/base/4.3}CharacterStringType" minOccurs="0"/&gt;
 *         &lt;element name="delayType" type="{http://www.fixm.aero/flight/4.3}PlannedDelayTypeType"/&gt;
 *         &lt;element name="delayValue" type="{http://www.fixm.aero/base/4.3}DurationType"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}PlannedDelayExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficeTRQ_PlannedDelayType")
public class FficeTRQPlannedDelayType
    extends PlannedDelayType
    implements Serializable
{

    private static final long serialVersionUID = 1L;

}
