//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A class that defines a constraint to a route point or trajectory.
 * 
 * &lt;p&gt;Java class for FficePS_RouteTrajectoryConstraintType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficePS_RouteTrajectoryConstraintType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.fixm.aero/flight/4.3}RouteTrajectoryConstraintType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="departureOrArrivalIndicator" type="{http://www.fixm.aero/flight/4.3}DepartureOrArrivalIndicatorType" minOccurs="0"/&gt;
 *         &lt;element name="description" type="{http://www.fixm.aero/base/4.3}CharacterStringType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}RouteTrajectoryConstraintExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="level" type="{http://www.fixm.aero/flight/4.3}FficePS_LevelConstraintType" minOccurs="0"/&gt;
 *         &lt;element name="restrictionReference" type="{http://www.fixm.aero/base/4.3}RestrictionReferenceType" minOccurs="0"/&gt;
 *         &lt;element name="speed" type="{http://www.fixm.aero/flight/4.3}FficePS_SpeedConstraintType" minOccurs="0"/&gt;
 *         &lt;element name="time" type="{http://www.fixm.aero/flight/4.3}FfficePS_TimeConstraintType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficePS_RouteTrajectoryConstraintType")
public class FficePSRouteTrajectoryConstraintType
    extends RouteTrajectoryConstraintType
    implements Serializable
{

    private static final long serialVersionUID = 1L;

}
