//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A data container supporting the representation of aircraft movement descriptions with variable levels of granularity.  This container enables the representation of a flight route and a 4D trajectory, as described in ICAO Doc 9965 Volume 2.  [FIXM]
 * 
 * &lt;p&gt;Java class for FficeTRP_RouteTrajectoryGroupType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficeTRP_RouteTrajectoryGroupType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.fixm.aero/flight/4.3}RouteTrajectoryGroupType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="climbProfile" type="{http://www.fixm.aero/flight/4.3}FficeTRP_PerformanceProfileType" minOccurs="0"/&gt;
 *         &lt;element name="climbSchedule" type="{http://www.fixm.aero/flight/4.3}FficeTRP_SpeedScheduleType" minOccurs="0"/&gt;
 *         &lt;element name="descentProfile" type="{http://www.fixm.aero/flight/4.3}FficeTRP_PerformanceProfileType" minOccurs="0"/&gt;
 *         &lt;element name="descentSchedule" type="{http://www.fixm.aero/flight/4.3}FficeTRP_SpeedScheduleType" minOccurs="0"/&gt;
 *         &lt;element name="element" type="{http://www.fixm.aero/flight/4.3}FficeTRP_RouteTrajectoryElementType" maxOccurs="2000" minOccurs="2"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}RouteTrajectoryGroupExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="routeInformation" type="{http://www.fixm.aero/flight/4.3}FficeTRP_FlightRouteInformationType"/&gt;
 *         &lt;element name="takeoffMass" type="{http://www.fixm.aero/base/4.3}MassType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficeTRP_RouteTrajectoryGroupType")
public class FficeTRPRouteTrajectoryGroupType
    extends RouteTrajectoryGroupType
    implements Serializable
{

    private static final long serialVersionUID = 1L;

}
