//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.base;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * An identifiable, responsible entity that can be either a natural person or an organization.
 * 
 * &lt;p&gt;Java class for FficeFPU_PersonOrOrganizationType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FficeFPU_PersonOrOrganizationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.fixm.aero/base/4.3}PersonOrOrganizationType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="contact" type="{http://www.fixm.aero/base/4.3}ContactInformationType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}PersonOrOrganizationExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="identifier" type="{http://www.fixm.aero/base/4.3}CharacterStringType"/&gt;
 *         &lt;element name="identifierDomain" type="{http://www.fixm.aero/base/4.3}CharacterStringType"/&gt;
 *         &lt;element name="name" type="{http://www.fixm.aero/base/4.3}TextNameType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FficeFPU_PersonOrOrganizationType")
public class FficeFPUPersonOrOrganizationType
    extends PersonOrOrganizationType
    implements Serializable
{

    private static final long serialVersionUID = 1L;

}
